# fly.toml app configuration file generated for autumn-resonance-4449 on 2023-10-18T17:53:04+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "autumn-resonance-4449"
primary_region = "arn"

[build]

[deploy]
  strategy = "bluegreen"

[env]
  PORT = "3003"

[processes]
  app = "node app.js"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
