# fly.toml app configuration file generated for autumn-resonance-4449 on 2023-10-17T14:33:54+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "autumn-resonance-4449"
primary_region = "arn"

[deploy]
  strategy = "bluegreen"

[processes]
  app = "node app.js"

[build]
  [build.args]
    NODE_VERSION = "16.9.0"

[env]
  PORT = "3003"

[http_service]
  internal_port = 3003
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
