name: Deployment Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  Deployment-Pipeline:
    runs-on: ubuntu-20.04
    if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message), '#SKIP') }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.9.0'
      - name: log directory info
        run: ls -l
      - name: frontend - npm install
        run: cd bloglist-frontend && ls -l && npm install
      - name: check current directory
        run: ls -l
      - name: frontend - eslint
        run: cd bloglist-frontend && npm run lint
      - name: frontend - tests
        run: cd bloglist-frontend && npm run test
      - name: frontend - build
        run: cd bloglist-frontend && npm run build
      - name: backend - npm install
        run: cd bloglist-backend && ls -l && npm install
      - name: backend - eslint
        run: cd bloglist-backend && npm run lint
      - name: backend - tests
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}
          SECRET: ${{ secrets.SECRET }}
        run: cd bloglist-backend && npm run test &> out-test-logs.txt
      - name: store to env
        run: |
          echo 'CONTENT_ENV<<EOF' >> $GITHUB_ENV
          cat out-test-logs.txt >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
        working-directory: ./bloglist-backend
      - name: echo env
        run: echo "$CONTENT_ENV"
      - name: did tests fail?
        env:
          HAS_FAILED: ${{contains(join(env.CONTENT_ENV), 'FAIL')}}
        run: echo "$HAS_FAILED"
      - name: go to failure if test failed
        if: ${{contains(join(env.CONTENT_ENV), 'FAIL')}}
        run: exit 1